project_id = "jhkxcplfempenoczcoep"

[functions.send-auth-email]
verify_jwt = false

[functions.create-auth-user]
verify_jwt = false

[functions.create-auth-users-batch]
verify_jwt = false

[functions.create-order]
verify_jwt = true

[functions.calculate-simulation]
verify_jwt = true
